[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
x_onchain = "4se6A74JXwE467VyoVpB9DcitWk9jd7Mf68XsbZ1r31T"

[programs.localnet]
x_onchain = "4se6A74JXwE467VyoVpB9DcitWk9jd7Mf68XsbZ1r31T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[cluster.devnet]
json_rpc_url = "https://api.devnet.solana.com"
websocket_url = "wss://api.devnet.solana.com"
commitment = "confirmed"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
